### PR TITLE
Get interfaces

### PR DESCRIPTION
**Pull request by jmrenshaw**
See issue #3 for details.

### CODE REVIEW

**Comment by dbarrosop** [comment]
Thanks for the PR, wait while we still fix the CI so we can make sure everything is tested before merged.

Thanks!

**Comment by GGabriele** [comment]
Hey @jmrenshaw , can you please take a look at @haderp message on #3 regarding last_flapped field?

**Comment by jmrenshaw** [comment]
Hi @GGabriele , yes I will have a look at using the command @haderp mentions to get the last_flapped information.

**Comment by GGabriele** [comment]
@jmrenshaw Awesome!

**Comment by jmrenshaw** [comment]
Think I've got it all sorted, that was my first proper rebase so apologies if I've monkey'd it all up :)

**Comment by GGabriele** [comment]
Thanks @jmrenshaw ! I still mess it up sometime while rebasing ;)

**Comment by GGabriele** [comment]
@jmrenshaw I'm really sorry about that, but would you mind to rebase this again? I totally forgot to merge it :(

**Comment by jmrenshaw** [comment]
Apologies for the hundreds of commits, still getting used to the whole rebasing thing.  Think its there.

**Pull request merged**
